config/routes.rb
Rails.application.routes.draw do

  resources :votes
  resources :questions do
      resources :comments
      resources :answers do
        resources :comments
      end
    end

  post 'questions/:question_id/answers/:answer_id' => 'comments#answer_create'

  get '/' => 'questions#index'
  get '/login' => 'users#login'
  put '/login' => 'users#update'
  get '/signup' => 'users#signup'
  post '/signup' => 'users#create'
  delete '/logout' => 'users#destroy'
  delete '/questions' => 'questions#index'
  post '/questions/:question_id/voteup' => 'votes#questionvoteup'
  post '/questions/:question_id/votedown' => 'votes#questionvotedown'
  post 'answers/:answer_id/voteup' => 'votes#answervoteup'
  post 'answers/:answer_id/votedown' => 'votes#answervotedown'
end

app/models/question.rb
class Question < ActiveRecord::Base
  include Voteable

  has_many :comments, as: :commentable
  has_many :answers
  belongs_to :asker, class_name: "User", foreign_key: "user_id"

  validates :title, presence: true, length: { in: 5..50}
  validates :content, presence: true

  def self.sort_popular
    all.sort_by{|question| question.total_votes}.reverse
  end

  def sort_popular_answers
    self.answers.sort_by{|answer| answer.total_votes}.reverse
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController


  # def new
  #   if session[:user_id]
  #     @user = User.find_by(id: session[:user_id])
  #     @question = @user.questions.new
  #   else
  #     redirect_to "/login"
  #   end
  # end

  def create
    @user = User.find_by(id: session[:user_id])
    @question = @user.questions.new(question_params)
    @question.save
    if request.xhr?
      render @question, layout: false
    else
      redirect_to questions_path
    end
  end

  def index
    session[:current_url] = questions_path
    @user = User.find_by(id: session[:user_id])
    @questions = Question.sort_popular
  end

  def show
    @user = User.find_by(id: session[:user_id])
    @question = Question.find(params[:id])
    session[:current_url] = question_path(@question)
  end

  def edit
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
      @question = Question.find(params[:id])
    else
      redirect_to "/login"
    end
  end

  def update
    @user = User.find_by(id: session[:user_id])
    @question = Question.find(params[:id])
    @question.update(question_params)
    redirect_to question_path
  end

  def destroy
      @user = User.find_by(id: session[:user_id])
      @question = Question.find(params[:id])
      @question.destroy
      redirect_to questions_path
  end

  private
  def question_params
    params.require(:question).permit(:title, :content)
  end

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in!!"
      redirect_to login_path
    end
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.erb
<h4><%= link_to("#{question.title}",question_path(question))%></h4>
<p> <%= question.content %> </p>

app/views/questions/edit.html.erb
<div class="container">
  <h1>Edit Question</h1>

  <%= form_for :question, url: question_path(@question), method: :patch do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>

  <% end %>

  <% if @question.asker == @user %>
  <%= form_for :question, :url => question_path(@question), :method => "delete" do %>
  <%= submit_tag("Delete") %>
  <% end %>
  <% end %>
</div>

app/views/questions/index.html.erb
<% if logged_in?%>
<div class="hidden_form">
  <div class="jumbotron">
    <h1>Ask A Question</h1>
    <%= form_for([@question, @user.questions.new], remote: true) do |f| %>
    <%= f.label :title %>
    <%= f.text_area :title, :class => 'question_text_area', :size => "50x1" %><br><br>
    <%= f.label :content %>
    <%= f.text_area :content, :class => 'question_text_area', :size => "50x7"%><br><br>
    <%= f.submit 'Create a New Question', :class => 'btn btn-lg btn-success' %>
    <% end %>
  </div>
</div>
<% end %>
<h1>All Questions</h1>
<div class="row marketing">
  <div class="col-lg-12">
    <div class="question_list">
      <% @questions.each do |question| %>
      <h4><%= link_to("#{question.title}",question_path(question))%></h4>
      <p> <%= question.content %> </p>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div>
  <h1>New Question</h1>

  <%= form_for @question do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br><br>
  <%= f.label :content %>
  <%= f.text_area :content %><br><br>
  <%= f.submit %>
  <% end %>

</div>

app/views/questions/show.html.erb
<a href="/questions/<%=@question.id%>/voteup" class="glyphicon glyphicon-thumbs-up question_up"></a>
<a href="/questions/<%=@question.id%>/votedown" class="glyphicon glyphicon-thumbs-down question_down"></a>
<div class="question_vote_count">
  <%= render 'votes/vote_div' %>
</div>

<div class="question_body">
  <h1><%= @question.title %></h1>
  <p><strong>Author: </strong><%= @question.asker.username %></p>
  <p><%= @question.content %></p>
</div>
<h3>Comments: </h3>
<div class="question_comment_list">
  <%= render @question.comments %>
</div>

<% if session[:user_id]!=nil %>
<div class="hidden_form">
  <h2>Add a Comment</h2>
  <%= render 'comments/form' %>
</div>
<% end %>


<% if @question.asker == @user %>
<%= link_to("Edit Question", edit_question_path(@question)) %>
<% end %>
<br><br>



<h2>Answers:</h2>
<div id="answer_list">
  <%= render @question.answers.sort_by{|answer| answer.total_votes}.reverse %>


  <% if session[:user_id]!=nil %>
  <div class="hidden_form">
    <h2>Add an Answer</h2>
    <%= render 'answers/form' %>
  </div>
  <% end %>
  <%= form_tag("/questions", :controller=>"users", :method=>"get") do %>
  <%= submit_tag "Back" %>
  <% end %>