config/routes.rb
Rails.application.routes.draw do

  resources :votes
  resources :questions do
      resources :comments
      resources :answers do
        resources :comments
      end
    end

  post 'questions/:question_id/answers/:answer_id' => 'comments#answer_create'

  get '/' => 'questions#index'
  get '/login' => 'users#login'
  put '/login' => 'users#update'
  get '/signup' => 'users#signup'
  post '/signup' => 'users#create'
  delete '/logout' => 'users#destroy'
  delete '/questions' => 'questions#index'
  post '/questions/:question_id/voteup' => 'votes#questionvoteup'
  post '/questions/:question_id/votedown' => 'votes#questionvotedown'
  post 'answers/:answer_id/voteup' => 'votes#answervoteup'
  post 'answers/:answer_id/votedown' => 'votes#answervotedown'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Voteable

  has_many :comments, as: :commentable
  belongs_to :question
  belongs_to :answerer, class_name: "User", foreign_key: "user_id"

  validates :content, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @user = User.find_by(id: session[:user_id])
    if @user
      @question = Question.find(params[:question_id])
      @answer = @question.answers.new(answer_params)
      @answer.user_id = @user.id
      @answer.save
      if request.xhr?
        puts "HEYYyYYyYYyyyyyyy"
        render @answer, layout: false
      else
        redirect_to session[:current_url]
      end
    else
      redirect_to '/login'
    end
  end

  def edit
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
      @question = Question.find(params[:question_id])
      @answer = Answer.find(params[:id])
    else
      redirect_to "/login"
    end
  end

  def update
    @user = User.find_by(id: session[:user_id])
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    @answer.update(answer_params)
    redirect_to question_path(@question)
  end

  def destroy
      @user = User.find_by(id: session[:user_id])
      @question = Question.find(params[:question_id])
      @answer = Answer.find(params[:id])
      @answer.destroy
      redirect_to question_path(@question)
  end

  private
  def answer_params
    params.require(:answer).permit(:content)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<a href="/answers/<%=answer.id%>/voteup" class="glyphicon glyphicon-thumbs-up answer_up" type="<%=answer.id%>"></a>
<a href="/answers/<%=answer.id%>/votedown" class="glyphicon glyphicon-thumbs-down answer_down" type="<%=answer.id%>"></a>
<div class="answer_vote_count<%=answer.id%>">
  <p>Votes: <%= answer.total_votes %></p>
</div>
  <div class="answer_body">
    <strong>Author: </strong><%= answer.answerer.username %><br>
    <strong>Answer: </strong><%= answer.content %><br>

    <% if session[:user_id]!=nil %>
    <div id="answer_comment<%=answer.id%>" class="answer_comments">
    <div class="answer_comment">
      <h2>Add a Comment</h2>
      <%= form_for :comment, url: question_answer_path(@question, answer), remote: true, html: { class: "new_answer_comment", id: "new_answer_comment"} do |f| %>
      <p>
        <%= f.label "Your comment: " %><br>
        <%= f.text_area :content, :class => 'comment_text_area'%>
      </p>
      <input type="hidden" value=<%=@user.id%> name="comment[user_id]"/>
      <p>
        <%= f.submit %>
      </p>
      <% end %>
    </div>
    </div>
    <% end %>

    <% if answer.comments.count != 0%>
    <ul>
      <h3>Comments: </h3>
    <% end %>
      <div class="answer_comment_list">
      <% answer.comments.each do |comment| %>
      <strong>Comment Author: </strong><%= comment.commenter.username %><br>
      <strong>Comment: </strong><%= comment.content %><br><br>
      <% end %>
      </div>
    </ul>


    <% if answer.answerer == @user %>
    <%= link_to("Edit Answer", edit_question_answer_path(@question, answer)) %>
    <% end %>
    <a href="answer_comment<%=answer.id%>" class="show_answer_comments_form">Add a comment</a>

    <br>
  </div>
</div><br>

app/views/answers/_form.html.erb
<%= form_for([@question, @answer || @question.answers.new ], remote: true) do |f| %>
  <p>
    <%= f.label "Your answer: " %><br>
    <%= f.text_area :content, :class => 'answer_text_area' %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/answers/edit.html.erb
<div class="container">
  <h1>Edit Answer</h1>

  <%= form_for([@question, @answer]) do |f| %>
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>

  <% end %>

  <% if @answer.answerer == @user %>
  <%= form_for([@question, @answer], :method => "delete") do %>
  <%= submit_tag("Delete") %>
  <% end %>
  <% end %>
</div>